services:
  smart-pju-fe:
    container_name: smart-pju-fe
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_VPS_HOST=localhost
    image: bayuhadi863/smart-pju-fe:latest
    ports:
      - "3000:80"
    restart: always
    environment:
      - VITE_VPS_HOST=localhost
